### ISSUE TITLE
Crash on multiplayer screen

### ISSUE THREAD

**Issue by jelebruh** [SeraphJACK/SimpleLogin#32]
Some players report bug when enter in multiplayer they minecraft crash with render error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	

[Full Log 1](https://jelebruh.xyz/files/simplelogin1.txt) 

[Full Log 2](https://jelebruh.xyz/files/simplelogin2.txt)

**Comment by SeraphJACK** [comment]
I don't see why Simple Login is to blame, it seems like `bmorph`'s issue.
